version: "3.8"

services:
  native-image-amd64:
    container_name: app-linux-amd64
    build:
      context: .
      target: graalvm-static
      args:
        JDK_VERSION: 17
    platform: amd64
    volumes:
      - ./:/src:rw
    command: [ "./httpserver" ]
    ports:
      - "8080:80"
    networks:
      - app-network

  native-image-arm64:
    container_name: app-linux-arm64
    build:
      context: .
      target: graalvm-static
      args:
        JDK_VERSION: 17
    platform: arm64
    volumes:
      - ./:/src:rw
    command: [ "./httpserver" ]
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network: