name: Greetings

on: [ pull_request, issues ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Greetings! Thanks for creating the issue.'
          pr-message: 'Greetings! Thanks for the PR.'
